#+title: zarrmony
#+subtitle: a general-purpose converter of all bioimage formats to ome-zarr
#+author: Max Ferrin
#+email: ferrin@calicolabs.com
#+last_modified: <2026-05-01 Fri 17:59>
#+OPTIONS: toc:t num:nil author:t date:t title:t ^:nil broken-links:mark

* Description
- a general-purpose automated imaging data converter that takes any
  file format as input as outputs standard OME-Zarr files
- see [[https://docs.google.com/document/d/1VXvMFzCBp0KDXIc2ymMxb6u2wDvE9yyvr0MKkbZEQLU/edit?tab=t.0#heading=h.siy2lgr7uqcr][Aperture Proposal]]
* Planning and progress notes
#+begin_quote
- project management stuff: what specific tasks to I plan to tackle when?
- record my thinking and decision-making process
  - changes to the original plan and rationale
  - is anything stumping me?
- when discussing specific code snippets, link to the headline in this document
  where the code is located
#+end_quote
* Code
** Environment initial setup

This block creates the virtual environment, installs dependencies, and registers the project-specific Jupyter kernel.

#+begin_src bash :results raw drawer
# Create the pyproject.toml file
uv init --quiet

# Get rid of extra files generated by uv
rm main.py
rm README.md

# Create the virtual environment
uv venv

# Install jupyter
uv add jupyter

# Register the kernel that .dir-locals.el is configured to use
uv run python -m ipykernel install --user --name="zarrmony" --display-name="Python (zarrmony)"

# Force a refresh of the kernel list so Emacs can find the new one
uv run jupyter kernelspec list --json > /dev/null
#+end_src

#+RESULTS:
:results:
Installed kernelspec zarrmony in /Users/ferrin/Library/Jupyter/kernels/zarrmony
:end:

Refresh kernelspecs in emacs:
#+begin_src emacs-lisp :tangle no
(jupyter-refresh-kernelspecs)
#+end_src

#+RESULTS:
: Refreshing kernelspecs...done

** Install packages
#+begin_src bash :results raw drawer
uv add bioio
#+end_src

#+RESULTS:
:results:
:end:

Additional packages can always be installed down the line with ~uv add [package]~

** Github repo initial setup
/github CLI ~gh~ needs to be installed/

#+begin_src bash :results raw drawer
# Initialize local git repository
git add .
git commit -m "Initial commit from cookiecutter template"

# Create Github repository and push
# Replace 'private' with 'public' if desired
gh repo create zarrmony --public --source=. --remote=origin --push
#+end_src

#+RESULTS:
:results:
[main (root-commit) 2411c05] Initial commit from cookiecutter template
 8 files changed, 2302 insertions(+)
 create mode 100644 .dir-locals.el
 create mode 100644 .gitignore
 create mode 100644 .python-version
 create mode 100644 README.org
 create mode 100644 pyproject.toml
 create mode 100644 uv.lock
 create mode 100644 zarrmony_functions.py
 create mode 100644 zarrmony_notebook.org
https://github.com/ferrinm/zarrmony
branch 'main' set up to track 'origin/main'.
:end:

This should now be accessible at https://github.com/ferrinm/zarrmony/blob/main/README.org

** Example use code
:PROPERTIES:
:header-args:python: :tangle no :kernel zarrmony :session zarrmony
:END:

#+begin_quote
Put code here that should be interactively run by the "end user" to analyze
their data in notebook format. Transfer as much boilerplate code as possible to
the [[* Source code][Source code]] section in order to improve readability and usability.
#+end_quote

#+begin_src python :results raw
import matplotlib.pyplot as plt
import matplotlib
import numpy as np

from skimage import data

fig, axs = plt.subplots(nrows=3, ncols=3)
for ax in axs.flat:
    ax.axis("off")
axs[0, 0].imshow(data.astronaut())
axs[0, 1].imshow(data.binary_blobs(), cmap=plt.cm.gray)
axs[0, 2].imshow(data.brick(), cmap=plt.cm.gray)
axs[1, 0].imshow(data.colorwheel())
axs[1, 1].imshow(data.camera(), cmap=plt.cm.gray)
axs[1, 2].imshow(data.cat())
axs[2, 0].imshow(data.checkerboard(), cmap=plt.cm.gray)
axs[2, 1].imshow(data.clock(), cmap=plt.cm.gray)
further_img = np.full((300, 300), 255)
for xpos in [100, 150, 200]:
    further_img[150 - 10 : 150 + 10, xpos - 10 : xpos + 10] = 0
axs[2, 2].imshow(further_img, cmap=plt.cm.gray)
plt.subplots_adjust(wspace=0.1, hspace=0.1)
#+end_src
*** setup
**** set project paths
#+begin_src python
import os

working_dir = os.getcwd()
raw_data_dir = os.path.join(working_dir,'data/raw')
processed_data_dir = os.path.join(working_dir,'data/processed')
fig_dir = os.path.join(working_dir,'figures')
#+end_src


**** import custom functions
#+begin_src python
import sys
from importlib import reload

from zarrmony_functions import *
reload(sys.modules['zarrmony_functions'])
from zarrmony_functions import *
#+end_src

*** analysis step 1
** Source code
:PROPERTIES:
:header-args:python: :tangle zarrmony_functions.py :kernel zarrmony :session zarrmony
:END:
#+begin_quote
This contains custom functions and classes that are called from the [[* Production analysis code][Production
analysis code]] section. The "end user" should not need to look at any of this.
Everything inside here gets tangled to a separate code file unless explicitly
disabled.
#+end_quote
*** emacs setup

#+begin_src python

import IPython
from tabulate import tabulate

class OrgFormatter(IPython.core.formatters.BaseFormatter):
    def __call__(self, obj):
        try:
            return tabulate(obj, headers='keys',
                            tablefmt='orgtbl', showindex='always')
        except:
            return None

ip = get_ipython()
ip.display_formatter.formatters['text/org'] = OrgFormatter()
#+end_src

#+RESULTS:
:results:
:end:

** Prototyping area
:PROPERTIES:
:header-args:python: :tangle no :kernel zarrmony :session zarrmony
:END:

#+begin_quote
This is a temporary staging area for trying out new ideas. As things become more
polished and useful, reorganize them to [[* Production analysis code][Production analysis code]] or
[[* Source code][Source code]] as soon as possible. Non-directly useful bits of code can still stay
here as a record of what I tried, but still keep it as organized as possible.
#+end_quote
